# Project: PBL2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o DAL/CategoryDAL.o DAL/FoodDAL.o BLL/CategoryBLL.o BLL/FoodBLL.o DAL/DatabaseConnection.o UI/FoodUI.o UI/MainUI.o DAL/UserDAL.o BLL/UserBLL.o UI/AdminUI.o UI/ConsoleUI.o BLL/TableBLL.o BLL/BillBLL.o DAL/BillDAL.o DAL/TableDAL.o UI/TableUI.o UI/CategoryUI.o
LINKOBJ  = main.o DAL/CategoryDAL.o DAL/FoodDAL.o BLL/CategoryBLL.o BLL/FoodBLL.o DAL/DatabaseConnection.o UI/FoodUI.o UI/MainUI.o DAL/UserDAL.o BLL/UserBLL.o UI/AdminUI.o UI/ConsoleUI.o BLL/TableBLL.o BLL/BillBLL.o DAL/BillDAL.o DAL/TableDAL.o UI/TableUI.o UI/CategoryUI.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -lodbc32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = PBL2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

DAL/CategoryDAL.o: DAL/CategoryDAL.cpp
	$(CPP) -c DAL/CategoryDAL.cpp -o DAL/CategoryDAL.o $(CXXFLAGS)

DAL/FoodDAL.o: DAL/FoodDAL.cpp
	$(CPP) -c DAL/FoodDAL.cpp -o DAL/FoodDAL.o $(CXXFLAGS)

BLL/CategoryBLL.o: BLL/CategoryBLL.cpp
	$(CPP) -c BLL/CategoryBLL.cpp -o BLL/CategoryBLL.o $(CXXFLAGS)

BLL/FoodBLL.o: BLL/FoodBLL.cpp
	$(CPP) -c BLL/FoodBLL.cpp -o BLL/FoodBLL.o $(CXXFLAGS)

DAL/DatabaseConnection.o: DAL/DatabaseConnection.cpp
	$(CPP) -c DAL/DatabaseConnection.cpp -o DAL/DatabaseConnection.o $(CXXFLAGS)

UI/FoodUI.o: UI/FoodUI.cpp
	$(CPP) -c UI/FoodUI.cpp -o UI/FoodUI.o $(CXXFLAGS)

UI/MainUI.o: UI/MainUI.cpp
	$(CPP) -c UI/MainUI.cpp -o UI/MainUI.o $(CXXFLAGS)

DAL/UserDAL.o: DAL/UserDAL.cpp
	$(CPP) -c DAL/UserDAL.cpp -o DAL/UserDAL.o $(CXXFLAGS)

BLL/UserBLL.o: BLL/UserBLL.cpp
	$(CPP) -c BLL/UserBLL.cpp -o BLL/UserBLL.o $(CXXFLAGS)

UI/AdminUI.o: UI/AdminUI.cpp
	$(CPP) -c UI/AdminUI.cpp -o UI/AdminUI.o $(CXXFLAGS)

UI/ConsoleUI.o: UI/ConsoleUI.cpp
	$(CPP) -c UI/ConsoleUI.cpp -o UI/ConsoleUI.o $(CXXFLAGS)

BLL/TableBLL.o: BLL/TableBLL.cpp
	$(CPP) -c BLL/TableBLL.cpp -o BLL/TableBLL.o $(CXXFLAGS)

BLL/BillBLL.o: BLL/BillBLL.cpp
	$(CPP) -c BLL/BillBLL.cpp -o BLL/BillBLL.o $(CXXFLAGS)

DAL/BillDAL.o: DAL/BillDAL.cpp
	$(CPP) -c DAL/BillDAL.cpp -o DAL/BillDAL.o $(CXXFLAGS)

DAL/TableDAL.o: DAL/TableDAL.cpp
	$(CPP) -c DAL/TableDAL.cpp -o DAL/TableDAL.o $(CXXFLAGS)

UI/TableUI.o: UI/TableUI.cpp
	$(CPP) -c UI/TableUI.cpp -o UI/TableUI.o $(CXXFLAGS)

UI/CategoryUI.o: UI/CategoryUI.cpp
	$(CPP) -c UI/CategoryUI.cpp -o UI/CategoryUI.o $(CXXFLAGS)
